@BlazorTodo_HostAddress = https://localhost:7172

GET {{BlazorTodo_HostAddress}}/todoitems/
Accept: application/json

###

GET {{BlazorTodo_HostAddress}}/todoitems/complete
Accept: application/json

###

GET {{BlazorTodo_HostAddress}}/todoitems/2

###

Post {{BlazorTodo_HostAddress}}/todoitems
Content-Type: application/json

{
  "name": "Test drive Jeep CJ",
  "isComplete": false
}

###

Put {{BlazorTodo_HostAddress}}/todoitems/1
Content-Type: application/json

{
  "id": 1,
  "name": "Make coffee",
  "isComplete": true
}

###

DELETE {{BlazorTodo_HostAddress}}/todoitems/4

###
